### ISSUE TITLE
"I am REMOTE" Prompt in every session

### ISSUE THREAD

**Issue by briggsmBJ** [jdhitsolutions/New-ISERemoteTab#10]
$session = new-pssession $hname
        Invoke-Command -session $session -scriptblock{
        
            function prompt
            {
              Write-Host "  You are in a remote session!!  "  -NoNewline -ForegroundColor Red -BackgroundColor Yellow
              Write-Host "  "  -NoNewline
              write-host $(get-location) -nonewline
              return "--> "
            }
        
        }

is there any way to implement a prompt using enter-pssession only?  I love and use YOUR module every day.. Thank you!!

**Comment by jdhitsolutions** [comment]
I don't think I'd want to hardcode a remote prompt function.  You should be able to use the `-Profile` parameter and specify the path to a local ps1 file which can include your custom prompt function.

**Comment by jdhitsolutions** [comment]
Although I think I'll have to revisit this to make it easier with a multiline function.

**Comment by briggsmBJ** [comment]
Thanks.. I've been burned 2x this week already when a remote session suddenly dropped and I wasn't paying attention!!  I do have a one-off module (etsn2) for remoting from the shell, but I really love the ctrl+shift+T to open a new tab in ISE!

**Comment by jdhitsolutions** [comment]
Update the module to v2.0.0 and try again. I suggest defining your function in a profile script as I did in the [sample](https://github.com/jdhitsolutions/New-ISERemoteTab/blob/master/SampleRemoteProfile.ps1).

![image](https://user-images.githubusercontent.com/12089920/124318471-b4a77880-db46-11eb-8a67-3f456120d98c.png)

v2.0.0 has a number of breaking changes which is why there is a big bump in the version number. Let me know how this works for you.

**Comment by briggsmBJ** [comment]
Thanks.. I am able to get the profile working!   I do have to hardcode the -profilescript for NEW-ISERemoteTab though.  The variable $ISERemoteProfile doesn't seem to work for New-ISERemoteTab

![image](https://user-images.githubusercontent.com/50636870/124496271-7395ab00-dd76-11eb-8fbc-0991b4536337.png)


 It does seem to work for NEW-ISERemoteForm though.

Maybe this is expected.  Just an FYI

thank you very much for this module!

**Comment by jdhitsolutions** [comment]
I may have made the documentation confusing. The `$ISERemoteProfile` variable is for use with the form command only. But, what I could do is add a PSDefaultParameterValue in place of the variable.

**Comment by briggsmBJ** [comment]
It's working perfectly this way.. Just wanted to let you know.  Thanks again!

**Comment by jdhitsolutions** [comment]
I just pushed v2.1.0 to the PowerShell Gallery. `New-ISERemoteTab` will now use `$ISERemoteProfile` by default. So if you set it in your profile, manually, or using the form, if you run `New-ISERemoteTab -computername foo` AND have a remote profile script defined, it will be used.

**Comment by briggsmBJ** [comment]
works great!  thanks again..
